<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>consulo.internal.com.dslplatform</groupId>
	<artifactId>dsl-json-integration-tests-jpms-api</artifactId>
	<name>DSL-JSON integration tests (JPMS api module)</name>
	<description>DSL Platform compatible JSON (https://dsl-platform.com)</description>
	<url>https://github.com/ngs-doo/dsl-json</url>
	<packaging>jar</packaging>
	<version>3.0.3</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.deploy.skip>true</maven.deploy.skip>
	</properties>

	<dependencies>
		<dependency>
			<groupId>consulo.internal.com.dslplatform</groupId>
			<artifactId>dsl-json</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.jspecify</groupId>
			<artifactId>jspecify</artifactId>
			<version>1.0.1</version>
		</dependency>
	</dependencies>

	<licenses>
		<license>
			<name>The BSD 3-Clause License</name>
			<url>http://opensource.org/licenses/BSD-3-Clause</url>
		</license>
	</licenses>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.14.1</version>
				<configuration>
					<release>21</release>
					<useIncrementalCompilation>false</useIncrementalCompilation>
					<proc>full</proc>
					<annotationProcessorPaths>
						<path>
							<groupId>consulo.internal.com.dslplatform</groupId>
							<artifactId>dsl-json-processor</artifactId>
							<version>${project.version}</version>
						</path>
					</annotationProcessorPaths>
					<compilerArgs>
						<arg>-Adsljson.unknown=WARNING</arg>
					</compilerArgs>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
